spring:
    datasource:
        url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=disable
        username: ${PGUSER}
        password: ${PGPASSWORD}
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: validate
